import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import { schemaWorkspace } from "../src/commands/schema.js";
import { schemaContract } from "../src/contract.js";

test("schemaContract describes stable AI output contracts", () => {
  const schema = schemaContract();

  assert.equal(schema.name, "aienvmp-contract");
  assert.equal(schema.contractVersion, "0.1-prototype");
  assert.equal(schema.stableFrom, "0.2.0");
  assert.match(schema.compatibilityPolicy, /backward-compatible/);
  assert.match(schema.breakingChangePolicy, /contractVersion bump/);
  assert.equal(schema.recommendation.category, "AI workspace coordination");
  assert.match(schema.recommendation.positioning, /AI workspace coordination tool/);
  assert.match(schema.recommendation.positioning, /not a full SBOM scanner/);
  assert.match(schema.recommendation.differentiators.join(" "), /intent, checkpoint, timeline, and handoff/);
  assert.match(schema.recommendation.differentiators.join(" "), /start --json root recovery fields/);
  assert.match(schema.recommendation.differentiators.join(" "), /aiDiscovery\.decision/);
  assert.match(schema.recommendation.differentiators.join(" "), /aiEntry/);
  assert.match(schema.recommendation.differentiators.join(" "), /copyPastePrompt/);
  assert.match(schema.recommendation.differentiators.join(" "), /startupChecklist/);
  assert.match(schema.recommendation.differentiators.join(" "), /auto-ready versus fallback-required/);
  assert.match(schema.recommendation.differentiators.join(" "), /dependencyCoordination/);
  assert.match(schema.recommendation.differentiators.join(" "), /publishGate/);
  assert.match(schema.recommendation.differentiators.join(" "), /dependency-free local operation/);
  assert.match(schema.recommendation.keepInstalledWhen.join(" "), /future AI sessions/);
  assert.match(schema.recommendation.recommendWhen.join(" "), /multiple AI agents/);
  assert.match(schema.recommendation.recommendWhen.join(" "), /light SBOM/);
  assert.equal(schema.recommendation.adoptionChecklist[0].signal, "shared AI workspace");
  assert.match(schema.recommendation.adoptionChecklist.map((item) => item.ask).join(" "), /lockfiles/);
  assert.match(schema.recommendation.adoptionChecklist.map((item) => item.signal).join(" "), /version drift prevention/);
  assert.match(schema.recommendation.adoptionChecklist.map((item) => item.ask).join(" "), /different software versions/);
  assert.match(schema.recommendation.adoptionChecklist.map((item) => item.signal).join(" "), /fallback AI startup path/);
  assert.match(schema.recommendation.adoptionChecklist.map((item) => item.signal).join(" "), /human\/AI dashboard parity/);
  assert.match(schema.recommendation.adoptionChecklist.map((item) => item.ask).join(" "), /start --json discoveryDecision/);
  assert.match(schema.recommendation.adoptionChecklist.map((item) => item.ask).join(" "), /aiEntry/);
  assert.match(schema.recommendation.adoptionChecklist.map((item) => item.ask).join(" "), /copyPastePrompt/);
  assert.match(schema.recommendation.adoptionChecklist.map((item) => item.ask).join(" "), /fallbackPrompt/);
  assert.match(schema.recommendation.adoptionChecklist.map((item) => item.signal).join(" "), /dependency coordination need/);
  assert.match(schema.recommendation.adoptionChecklist.map((item) => item.signal).join(" "), /full SBOM boundary understood/);
  assert.match(schema.recommendation.doNotRecommendWhen.join(" "), /full compliance SBOM/);
  assert.match(schema.recommendation.shortPitch, /lightweight env map, light SBOM, intent log, and handoff/);
  assert.match(schema.recommendation.decisionRoutine.join(" "), /demo first/);
  assert.match(schema.recommendation.decisionRoutine.join(" "), /start --json root aiEntry/);
  assert.match(schema.recommendation.decisionRoutine.join(" "), /copyPastePrompt/);
  assert.match(schema.recommendation.decisionRoutine.join(" "), /auto-ready versus fallback-required/);
  assert.match(schema.recommendation.decisionRoutine.join(" "), /dashboard/);
  assert.match(schema.recommendation.decisionRoutine.join(" "), /scanner evidence boundaries/);
  assert.match(schema.recommendation.decisionRoutine.join(" "), /hard lock manager/);
  assert.match(schema.recommendation.decisionRoutine.join(" "), /shared AI coding workspace signals/);
  assert.match(schema.recommendation.discoverySignals.join(" "), /Codex, Claude, Gemini/);
  assert.match(schema.recommendation.discoverySignals.join(" "), /version drift/);
  assert.match(schema.recommendation.discoverySignals.join(" "), /different AI agents/);
  assert.match(schema.recommendation.discoverySignals.join(" "), /AI-readable environment map/);
  assert.match(schema.recommendation.discoverySignals.join(" "), /start --json copyPastePrompt recovery path/);
  assert.deepEqual(schema.recommendation.firstCommands, ["aienvmp start", "aienvmp onboard", "aienvmp context --json"]);
  assert.equal(schema.recommendation.proofCommand, "aienvmp demo");
  assert.ok(schema.recommendation.evidenceDocs.includes("examples/ai-adoption-guide.md"));
  assert.ok(schema.recommendation.evidenceDocs.includes("examples/ai-workspace-case-study.md"));
  assert.ok(schema.recommendation.evidenceDocs.includes("examples/multi-agent-conflict.md"));
  assert.match(schema.recommendation.rule, /not as a replacement/);
  assert.match(schema.aiAdoptionDecision.purpose, /Shortest AI-readable decision block/);
  assert.match(schema.aiAdoptionDecision.position, /AI workspace coordination tool/);
  assert.match(schema.aiAdoptionDecision.useWhen.join(" "), /multiple AI agents/);
  assert.match(schema.aiAdoptionDecision.useWhen.join(" "), /lockfiles/);
  assert.deepEqual(schema.aiAdoptionDecision.startWith, ["aienvmp start", "aienvmp onboard", "aienvmp context --json"]);
  assert.equal(schema.aiAdoptionDecision.fallbackWhenDiscoveryMissed.fallbackValue, "fallback-required");
  assert.equal(schema.aiAdoptionDecision.fallbackWhenDiscoveryMissed.pastePromptField, "copyPastePrompt");
  assert.match(schema.aiAdoptionDecision.fallbackWhenDiscoveryMissed.rule, /Do not assume/);
  assert.match(schema.aiAdoptionDecision.skipWhen.join(" "), /full compliance SBOM/);
  assert.equal(schema.aiAdoptionDecision.proofCommand, "aienvmp demo --json");
  assert.match(schema.aiAdoptionDecision.rule, /compact decision block/);
  assert.ok(schema.aiBootstrapFields.includes("nextSafeCommandSource"));
  assert.ok(schema.aiBootstrapFields.includes("nextSafeCommandReason"));
  assert.ok(schema.aiSessionFields.includes("ifMissingOrStale"));
  assert.ok(schema.aiSessionFields.includes("beforeEnvironmentChange"));
  assert.ok(schema.aiSessionFields.includes("handoff"));
  assert.ok(schema.aiSessionFields.includes("avoid"));
  assert.equal(schema.readOrder[0], ".aienvmp/discovery.json");
  assert.equal(schema.readOrder[1], ".aienvmp/README.md");
  assert.equal(schema.readOrder[2], ".aienvmp/status.json");
  assert.match(schema.readOrderRule, /instruction-file pointers/);
  assert.deepEqual(schema.followUpPlanFields, ["status", "count", "targets", "readFirst", "nextCommand", "commands", "reason", "rule"]);
  assert.deepEqual(schema.coordinationResolutionFields, ["status", "mode", "targets", "readFirst", "nextCommand", "steps", "commands", "mustNotDo", "rule"]);
  assert.ok(schema.environmentChangeProtocolFields.includes("beforeChange"));
  assert.ok(schema.environmentChangeProtocolFields.includes("mustNotDo"));
  assert.equal(schema.operationalSafety.mode, "advisory-first");
  assert.equal(schema.operationalSafety.defaultBehavior, "warn-only");
  assert.match(schema.operationalSafety.strictUse, /CI, release/);
  assert.match(schema.operationalSafety.mustNotDo.join(" "), /do not install, upgrade, downgrade/);
  assert.match(schema.operationalSafety.mustNotDo.join(" "), /audit fix/);
  assert.ok(schema.operationalSafety.allowedWithoutIntent.includes("read generated artifacts"));
  assert.ok(schema.operationalSafety.requireIntentBefore.includes("dependency or lockfile changes"));
  assert.equal(schema.qualitySignals.status, "prototype-hardening");
  assert.ok(schema.qualitySignals.principles.includes("AI-friendly"));
  assert.ok(schema.qualitySignals.principles.includes("batched-release"));
  assert.match(schema.qualitySignals.checks.map((item) => item.name).join(" "), /Operational safety/);
  assert.match(schema.qualitySignals.checks.map((item) => item.evidence).join(" "), /npm run release:check/);
  assert.match(schema.qualitySignals.recommendWhenAllTrue.join(" "), /fallback prompt/);
  assert.match(schema.qualitySignals.mustStayTrue.join(" "), /do not publish every small commit/);
  assert.equal(schema.aiLoop.name, "AI maintenance loop");
  assert.equal(schema.aiLoop.localMode, "warn-only");
  assert.deepEqual(schema.aiLoop.steps.map((item) => item.step), ["sync", "status", "context", "intent", "checkpoint", "handoff"]);
  assert.equal(schema.aiLoop.steps[0].command, "aienvmp sync");
  assert.equal(schema.aiLoop.steps[5].command, "aienvmp handoff");
  assert.match(schema.aiLoop.strictRule, /warn-only/);
  assert.equal(schema.agentDiscovery.mode, "best-effort-instruction-file-pointer");
  assert.equal(schema.agentDiscovery.startCommand, "aienvmp start");
  assert.equal(schema.agentDiscovery.discoverCommand, "aienvmp discover");
  assert.equal(schema.agentDiscovery.installCommand, "aienvmp onboard");
  assert.equal(schema.agentDiscovery.optionalInstallCommand, "aienvmp onboard --agents cursor,copilot");
  assert.match(schema.agentDiscovery.fallbackPrompt, /Use aienvmp as the workspace env map/);
  assert.match(schema.agentDiscovery.humanInstruction, /Paste copyPastePrompt/);
  assert.equal(schema.agentDiscovery.automaticDiscovery, "best-effort");
  assert.deepEqual(schema.agentDiscovery.decisionValues, ["auto-ready", "fallback-required"]);
  assert.match(schema.agentDiscovery.nextSetupCommand, /aienvmp onboard/);
  assert.match(schema.agentDiscovery.automaticDiscoveryLimit, /AI hosts only auto-read/);
  assert.equal(schema.agentDiscovery.fallbackCommand, "aienvmp start --json");
  assert.equal(schema.agentDiscovery.discoveryArtifact, ".aienvmp/discovery.json");
  assert.deepEqual(schema.agentDiscovery.fallbackRead, [".aienvmp/discovery.json", ".aienvmp/README.md", ".aienvmp/status.json", ".aienvmp/summary.md", "aienvmp context --json"]);
  assert.equal(schema.agentDiscovery.aiEntry.decision, "fallback-required");
  assert.equal(schema.agentDiscovery.aiEntry.copyPastePrompt, schema.agentDiscovery.copyPastePrompt);
  assert.equal(schema.agentDiscovery.copyPastePrompt, schema.agentDiscovery.fallbackPrompt);
  assert.ok(schema.agentDiscovery.promptUse.pasteInto.includes("Codex"));
  assert.match(schema.agentDiscovery.promptUse.when, /did not auto-read/);
  assert.ok(schema.agentDiscovery.optionalFiles.includes(".github/copilot-instructions.md"));
  assert.deepEqual(schema.agentDiscovery.files, ["AGENTS.md", "CLAUDE.md", "GEMINI.md"]);
  assert.match(schema.agentDiscovery.startupChecklist.join(" "), /dependencyQuickCheck/);
  assert.match(schema.agentDiscovery.startupChecklist.join(" "), /record intent before/);
  assert.ok(schema.agentDiscovery.sessionStart.includes("Start at .aienvmp/discovery.json when artifacts are present, then read .aienvmp/status.json."));
  assert.match(schema.agentDiscovery.rule, /shared live env map/);
  assert.equal(schema.demo.command, "aienvmp demo");
  assert.equal(schema.demo.jsonCommand, "aienvmp demo --json");
  assert.equal(schema.demo.scenario, "multi-agent-conflict");
  assert.match(schema.demo.workspaceImpact, /temporary workspace only/);
  assert.ok(schema.demo.expectedSignals.includes("artifactFreshness"));
  assert.equal(schema.sbomStrategy.mode, "light-by-default");
  assert.equal(schema.sbomStrategy.defaultCommand, "aienvmp sbom --json");
  assert.equal(schema.sbomStrategy.scannerCommand, "aienvmp sync --security");
  assert.ok(schema.sbomStrategy.externalTools.includes("syft"));
  assert.ok(schema.sbomStrategy.externalTools.includes("trivy"));
  assert.ok(schema.sbomStrategy.externalTools.includes("dependency-track"));
  assert.match(schema.sbomStrategy.evidenceWorkflow.join(" "), /light SBOM/);
  assert.match(schema.sbomStrategy.evidenceWorkflow.join(" "), /checkpoint and hand off/);
  assert.match(schema.sbomStrategy.interoperabilityRule, /AI workspace coordination layer/);
  assert.match(schema.sbomStrategy.aiRule, /optional scanners/);
  assert.equal(schema.releaseGate.mode, "manual-batched");
  assert.equal(schema.releaseGate.localCommand, "npm run release:check");
  assert.equal(schema.releaseGate.workflow, ".github/workflows/release.yml");
  assert.ok(schema.releaseGate.beforePublish.includes("npm run release:check"));
  assert.match(schema.releaseGate.rule, /batch meaningful changes/);
  assert.equal(schema.releaseReadiness.target, "0.2.0");
  assert.equal(schema.releaseReadiness.status, "prototype-hardening");
  assert.equal(schema.releaseReadiness.currentBatch.status, "accumulating");
  assert.equal(schema.releaseReadiness.currentBatch.releaseType, "stability-batch");
  assert.ok(schema.releaseReadiness.currentBatch.themes.includes("AI discovery"));
  assert.ok(schema.releaseReadiness.currentBatch.themes.includes("dependency quick check"));
  assert.ok(schema.releaseReadiness.currentBatch.themes.includes("dashboard parity"));
  assert.ok(schema.releaseReadiness.currentBatch.themes.includes("dashboard maintainability"));
  assert.ok(schema.releaseReadiness.currentBatch.themes.includes("AI quality signals"));
  assert.ok(schema.releaseReadiness.currentBatch.themes.includes("release gating"));
  assert.ok(schema.releaseReadiness.currentBatch.themes.includes("shared contract constants"));
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /aiDiscovery\.decision/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /fallback prompt contract/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /copyPastePrompt, promptUse, and aiEntry/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /plain start and discover output expose aiEntry/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /aiEntry and copyPastePrompt guidance/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /generated \.aienvmp\/README\.md and summary\.md surface aiEntry/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /dashboard rendering split/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /dashboard Agent Pointers/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /shows aiEntry fields/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /SBOM aiUse is visible/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /dependencyQuickCheck surfaced/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /demo --json exposes recommendationDecision/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /uses aiAdoptionDecision/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /dashboard Quality Signals mirrors aiAdoptionDecision/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /plain sbom and verbose status text/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /start --json exposes root-level discoveryDecision/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /AI adoption checklist/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /aiAdoptionDecision/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /version drift prevention/);
  assert.match(schema.releaseReadiness.currentBatch.changes.join(" "), /centralized AI discovery\/read-order constants/);
  assert.match(schema.releaseReadiness.currentBatch.reason, /one intentional release/);
  assert.equal(schema.releaseReadiness.publishDecision.default, "hold");
  assert.match(schema.releaseReadiness.publishDecision.batchThreshold, /Hold by default/);
  assert.match(schema.releaseReadiness.publishDecision.publishCandidateSignals.join(" "), /dashboard changes/);
  assert.match(schema.releaseReadiness.publishDecision.publishCandidateSignals.join(" "), /SBOM/);
  assert.match(schema.releaseReadiness.publishDecision.publishWhen.join(" "), /meaningful AI contract/);
  assert.match(schema.releaseReadiness.publishDecision.holdWhen.join(" "), /small documentation/);
  assert.match(schema.releaseReadiness.publishDecision.emergencyException, /Security/);
  assert.equal(schema.releaseReadiness.publishGate.status, "hold");
  assert.match(schema.releaseReadiness.publishGate.reason, /stability batch/);
  assert.match(schema.releaseReadiness.publishGate.nextAction, /do not npm publish/);
  assert.ok(schema.releaseReadiness.publishGate.requiredEvidence.includes("npm run release:check"));
  assert.match(schema.releaseReadiness.publishGate.readyWhen.join(" "), /release note group/);
  assert.match(schema.releaseReadiness.publishGate.readyWhen.join(" "), /aiDiscovery\.decision, aiUse, and dependencyQuickCheck/);
  assert.match(schema.releaseReadiness.publishGate.readyWhen.join(" "), /plain CLI review/);
  assert.match(schema.releaseReadiness.publishGate.readyWhen.join(" "), /generated artifact hints/);
  assert.match(schema.releaseReadiness.publishGate.readyWhen.join(" "), /dashboard fallback fields/);
  assert.match(schema.releaseReadiness.publishGate.readyWhen.join(" "), /shared AI discovery\/read-order constants/);
  assert.match(schema.releaseReadiness.publishGate.holdWhen.join(" "), /package\.json version/);
  assert.match(schema.releaseReadiness.publishGate.rule, /single AI-readable npm publish decision/);
  assert.match(schema.releaseReadiness.doNotPublishUntil.join(" "), /currentBatch changes/);
  assert.match(schema.releaseReadiness.doNotPublishUntil.join(" "), /package\.json version/);
  assert.ok(schema.releaseReadiness.requiredBeforeStable.includes("npm run release:check passes locally"));
  assert.ok(schema.releaseReadiness.requiredBeforeStable.includes("package metadata and CLI help match AI workspace coordination positioning"));
  assert.ok(schema.releaseReadiness.evidenceCommands.includes("npm run release:check"));
  assert.ok(schema.releaseReadiness.evidenceCommands.includes("node bin/aienvmp.js demo --json"));
  assert.match(schema.releaseReadiness.nextStabilizationTasks.join(" "), /freeze and review documented JSON root fields/);
  assert.match(schema.releaseReadiness.nextStabilizationTasks.join(" "), /aiAdoptionDecision/);
  assert.match(schema.releaseReadiness.nextStabilizationTasks.join(" "), /packaged skill/);
  assert.match(schema.releaseReadiness.nextStabilizationTasks.join(" "), /dashboard Quality Signals/);
  assert.match(schema.releaseReadiness.nextStabilizationTasks.join(" "), /Codex, Claude, Gemini, Cursor, and Copilot/);
  assert.match(schema.releaseReadiness.nextStabilizationTasks.join(" "), /CHANGELOG as one 0\.2\.0 release-note group/);
  assert.equal(schema.releaseReadiness.contractReview.status, "pending-0.2.0-review");
  assert.equal(schema.releaseReadiness.contractReview.command, "node bin/aienvmp.js schema --json");
  assert.ok(schema.releaseReadiness.contractReview.surfaces.includes("start"));
  assert.ok(schema.releaseReadiness.contractReview.surfaces.includes("sbom"));
  assert.ok(schema.releaseReadiness.contractReview.surfaces.includes("demo"));
  assert.ok(schema.releaseReadiness.contractReview.reviewFields.includes("outputs.*.rootFields"));
  assert.match(schema.releaseReadiness.contractReview.rule, /compatibility floor/);
  assert.ok(schema.releaseReadiness.stabilizationFocus.includes("AI session/status/context contract"));
  assert.ok(schema.releaseReadiness.stabilizationFocus.includes("aiDiscovery.decision and fallback startup contract"));
  assert.ok(schema.releaseReadiness.stabilizationFocus.includes("aiEntry and copyPastePrompt recovery contract across JSON, docs, examples, and packaged skill"));
  assert.ok(schema.releaseReadiness.stabilizationFocus.includes("aiEntry recovery visibility across generated artifacts and dashboard fallback surfaces"));
  assert.ok(schema.releaseReadiness.stabilizationFocus.includes("SBOM aiUse safety summary across JSON, summary, dashboard, and schema surfaces"));
  assert.ok(schema.releaseReadiness.stabilizationFocus.includes("dependencyQuickCheck across AI and human surfaces"));
  assert.ok(schema.releaseReadiness.stabilizationFocus.includes("dependencyQuickCheck across JSON, plain sbom, verbose status, summary, handoff, dashboard, and demo surfaces"));
  assert.ok(schema.releaseReadiness.stabilizationFocus.includes("dashboard maintainability helpers before further UI changes"));
  assert.match(schema.releaseReadiness.stableContractRule, /backward-compatible/);
  assert.match(schema.releaseReadiness.batchRule, /several meaningful/);
  assert.match(schema.releaseReadiness.batchRule, /one npm publish/);
  assert.equal(schema.dashboard.mode, "light-human-view");
  assert.equal(schema.dashboard.discoveryFallback.command, "aienvmp start --json");
  assert.equal(schema.dashboard.discoveryFallback.entry, ".aienvmp/discovery.json");
  assert.ok(schema.dashboard.discoveryFallback.decisionValues.includes("fallback-required"));
  assert.equal(schema.dashboard.discoveryFallback.nextSetupCommand, "aienvmp onboard");
  assert.match(schema.dashboard.discoveryFallback.startupChecklist.join(" "), /record intent before/);
  assert.deepEqual(schema.dashboard.discoveryFallback.read, [".aienvmp/discovery.json", ".aienvmp/README.md", ".aienvmp/status.json", ".aienvmp/summary.md", "aienvmp context --json"]);
  assert.equal(schema.dashboard.releaseDefaults.target, "0.2.0");
  assert.equal(schema.dashboard.releaseDefaults.evidence, "npm run release:check");
  assert.equal(schema.dashboard.qualityDefaults.evidence, "aienvmp start --json && aienvmp context --json");
  assert.deepEqual(schema.dashboard.essentialSurfaces.controlStrip, ["AI readiness", "Freshness", "Collaboration", "SBOM risk"]);
  assert.deepEqual(schema.dashboard.essentialSurfaces.tenSecondReview, ["AI entry", "Next command", "Review target", "Mode"]);
  assert.ok(schema.dashboard.essentialSurfaces.firstRead.includes("Maintenance"));
  assert.ok(schema.dashboard.essentialSurfaces.essentialCards.includes("Light SBOM"));
  assert.equal(schema.dashboard.surfaceBudget.mode, "essential-first");
  assert.equal(schema.dashboard.surfaceBudget.primaryReviewTime, "10 seconds");
  assert.ok(schema.dashboard.surfaceBudget.defaultPriority.includes("essentialCards"));
  assert.match(schema.dashboard.surfaceBudget.supportCardRule, /must not hide/);
  assert.match(schema.dashboard.rule, /10-second review/);
  assert.equal(schema.outputs.status.contract.name, "aienvmp-preflight");
  assert.equal(schema.outputs.discover.command, "aienvmp discover --json");
  assert.equal(schema.outputs.discover.mode, "read-only");
  assert.ok(schema.outputs.discover.rootFields.includes("detected"));
  assert.ok(schema.outputs.discover.rootFields.includes("aiDiscovery"));
  assert.ok(schema.outputs.discover.aiDiscoveryFields.includes("decision"));
  assert.ok(schema.outputs.discover.aiDiscoveryFields.includes("automatic"));
  assert.ok(schema.outputs.discover.aiDiscoveryFields.includes("fallbackRead"));
  assert.ok(schema.outputs.discover.aiDiscoveryFields.includes("nextSetupCommand"));
  assert.ok(schema.outputs.discover.aiDiscoveryFields.includes("startupChecklist"));
  assert.ok(schema.outputs.discover.aiDiscoveryFields.includes("sessionStart"));
  assert.ok(schema.outputs.discover.aiDiscoveryFields.includes("resume"));
  assert.ok(schema.outputs.discover.aiDiscoveryFields.includes("aiEntry"));
  assert.ok(schema.outputs.discover.resumeFields.includes("beforeEnvironmentChange"));
  assert.ok(schema.outputs.discover.resumeFields.includes("mustNotDo"));
  assert.ok(schema.outputs.discover.aiDiscoveryFields.includes("fallbackPrompt"));
  assert.ok(schema.outputs.discover.aiDiscoveryFields.includes("copyPastePrompt"));
  assert.ok(schema.outputs.discover.aiDiscoveryFields.includes("promptUse"));
  assert.ok(schema.outputs.discover.aiDiscoveryFields.includes("humanInstruction"));
  assert.match(schema.outputs.discover.purpose, /Zero-write detection/);
  assert.equal(schema.outputs.start.command, "aienvmp start --json");
  assert.equal(schema.outputs.start.mode, "read-mostly");
  assert.ok(schema.outputs.start.rootFields.includes("discoveryDecision"));
  assert.ok(schema.outputs.start.rootFields.includes("startupChecklist"));
  assert.ok(schema.outputs.start.rootFields.includes("resume"));
  assert.ok(schema.outputs.start.rootFields.includes("aiEntry"));
  assert.ok(schema.outputs.start.rootFields.includes("fallbackPrompt"));
  assert.ok(schema.outputs.start.rootFields.includes("copyPastePrompt"));
  assert.ok(schema.outputs.start.rootFields.includes("promptUse"));
  assert.match(schema.outputs.start.rule, /before assuming instruction-file automatic discovery worked/);
  assert.equal(schema.outputs.discovery.file, ".aienvmp/discovery.json");
  assert.equal(schema.outputs.discovery.format, "json");
  assert.ok(schema.outputs.discovery.rootFields.includes("decision"));
  assert.ok(schema.outputs.discovery.rootFields.includes("maintenance"));
  assert.ok(schema.outputs.discovery.maintenanceFields.includes("nextCommand"));
  assert.ok(schema.outputs.discovery.maintenanceFields.includes("dependencyQuickCheck"));
  assert.ok(schema.outputs.discovery.rootFields.includes("fallbackPrompt"));
  assert.ok(schema.outputs.discovery.rootFields.includes("aiEntry"));
  assert.ok(schema.outputs.discovery.rootFields.includes("copyPastePrompt"));
  assert.ok(schema.outputs.discovery.rootFields.includes("promptUse"));
  assert.match(schema.outputs.discovery.purpose, /Smallest generated fallback entry/);
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("nextAgent"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("readOrder"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("aiSession"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("aiBootstrap"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("nextSafeCommand"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("artifactFreshness"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("strictRecommendation"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("operationalSafety"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("qualitySignals"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("aiReadiness"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("collaboration"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("coordinationResolution"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("maintenanceLoop"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("followUps"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("followUpPlan"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("environmentChangeProtocol"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("agentPointers"));
  assert.ok(schema.outputs.status.contract.aiEntryFields.includes("dependencyQuickCheck"));
  assert.ok(schema.outputs.status.rootFields.includes("nextSafeCommand"));
  assert.ok(schema.outputs.status.rootFields.includes("readOrder"));
  assert.ok(schema.outputs.status.rootFields.includes("aiSession"));
  assert.ok(schema.outputs.status.rootFields.includes("aiBootstrap"));
  assert.ok(schema.outputs.status.rootFields.includes("artifactFreshness"));
  assert.ok(schema.outputs.status.rootFields.includes("strictRecommendation"));
  assert.ok(schema.outputs.status.rootFields.includes("operationalSafety"));
  assert.ok(schema.outputs.status.rootFields.includes("qualitySignals"));
  assert.ok(schema.outputs.status.rootFields.includes("followUpPlan"));
  assert.ok(schema.outputs.status.rootFields.includes("environmentChangeProtocol"));
  assert.ok(schema.outputs.status.rootFields.includes("dependencyQuickCheck"));
  assert.ok(schema.outputs.status.rootFields.includes("coordinationResolution"));
  assert.ok(schema.outputs.status.agentPointerFields.includes("discovery"));
  assert.ok(schema.outputs.status.agentPointerFields.includes("discoveryDecision"));
  assert.ok(schema.outputs.status.agentPointerFields.includes("nextSetupCommand"));
  assert.ok(schema.outputs.status.agentPointerFields.includes("startupChecklist"));
  assert.ok(schema.outputs.status.agentPointerFields.includes("onboardCommand"));
  assert.ok(schema.outputs.status.agentPointerFields.includes("fallbackRead"));
  assert.ok(schema.outputs.status.agentPointerFields.includes("fallbackCommand"));
  assert.equal(schema.outputs.startHere.file, ".aienvmp/README.md");
  assert.match(schema.outputs.startHere.purpose, /discover the \.aienvmp directory/);
  assert.deepEqual(schema.outputs.startHere.startsWith, ["read order", "AI session", "next"]);
  assert.ok(schema.outputs.status.agentPointerFields.includes("rule"));
  assert.equal(schema.outputs.summary.command, "aienvmp summary --write");
  assert.equal(schema.outputs.summary.format, "markdown");
  assert.deepEqual(schema.outputs.summary.startsWith, ["AI readiness", "AI signals", "AI start here", "AI next"]);
  assert.equal(schema.outputs.plan.command, "aienvmp plan --json");
  assert.ok(schema.outputs.plan.rootFields.includes("aiBootstrap"));
  assert.ok(schema.outputs.plan.rootFields.includes("nextSafeCommand"));
  assert.ok(schema.outputs.plan.rootFields.includes("followUpPlan"));
  assert.ok(schema.outputs.context.rootFields.includes("coordination"));
  assert.ok(schema.outputs.context.rootFields.includes("startHere"));
  assert.ok(schema.outputs.context.rootFields.includes("readOrder"));
  assert.ok(schema.outputs.context.rootFields.includes("aiSession"));
  assert.ok(schema.outputs.context.rootFields.includes("aiBootstrap"));
  assert.ok(schema.outputs.context.rootFields.includes("nextSafeCommand"));
  assert.ok(schema.outputs.context.rootFields.includes("artifactFreshness"));
  assert.ok(schema.outputs.context.rootFields.includes("strictRecommendation"));
  assert.ok(schema.outputs.context.rootFields.includes("operationalSafety"));
  assert.ok(schema.outputs.context.rootFields.includes("qualitySignals"));
  assert.ok(schema.outputs.context.rootFields.includes("collaboration"));
  assert.ok(schema.outputs.context.rootFields.includes("coordinationResolution"));
  assert.ok(schema.outputs.context.rootFields.includes("maintenanceLoop"));
  assert.ok(schema.outputs.context.rootFields.includes("agentPointers"));
  assert.ok(schema.outputs.context.rootFields.includes("followUpPlan"));
  assert.ok(schema.outputs.context.rootFields.includes("environmentChangeProtocol"));
  assert.ok(schema.outputs.context.rootFields.includes("dependencyQuickCheck"));
  assert.ok(schema.outputs.context.rootFields.includes("aiReadiness"));
  assert.ok(schema.outputs.handoff.rootFields.includes("dependencyHandoff"));
  assert.ok(schema.outputs.handoff.rootFields.includes("startHere"));
  assert.ok(schema.outputs.handoff.rootFields.includes("readOrder"));
  assert.ok(schema.outputs.handoff.rootFields.includes("aiBootstrap"));
  assert.ok(schema.outputs.handoff.rootFields.includes("nextSafeCommand"));
  assert.ok(schema.outputs.handoff.rootFields.includes("continuation"));
  assert.ok(schema.outputs.handoff.continuationFields.includes("resume"));
  assert.ok(schema.outputs.handoff.continuationFields.includes("discovery"));
  assert.ok(schema.outputs.handoff.resumeFields.includes("beforeEnvironmentChange"));
  assert.ok(schema.outputs.handoff.resumeFields.includes("mustNotDo"));
  assert.ok(schema.outputs.handoff.continuationFields.includes("followUpPlan"));
  assert.ok(schema.outputs.handoff.continuationFields.includes("coordinationResolution"));
  assert.ok(schema.outputs.handoff.continuationFields.includes("dependencyQuickCheck"));
  assert.ok(schema.outputs.handoff.rootFields.includes("coordination"));
  assert.ok(schema.outputs.handoff.rootFields.includes("coordinationResolution"));
  assert.equal(schema.outputs.sbom.command, "aienvmp sbom --json");
  assert.ok(schema.outputs.sbom.rootFields.includes("startHere"));
  assert.ok(schema.outputs.sbom.rootFields.includes("readOrder"));
  assert.ok(schema.outputs.sbom.rootFields.includes("aiBootstrap"));
  assert.ok(schema.outputs.sbom.rootFields.includes("nextSafeCommand"));
  assert.ok(schema.outputs.sbom.rootFields.includes("scannerGuidance"));
  assert.ok(schema.outputs.sbom.scannerGuidanceFields.includes("decision"));
  assert.ok(schema.outputs.sbom.scannerGuidanceFields.includes("requireScannerFor"));
  assert.ok(schema.outputs.sbom.scannerGuidanceFields.includes("externalTools"));
  assert.ok(schema.outputs.sbom.scannerGuidanceFields.includes("evidenceWorkflow"));
  assert.ok(schema.outputs.sbom.scannerGuidanceFields.includes("interoperabilityRule"));
  assert.ok(schema.outputs.sbom.scannerGuidanceFields.includes("whenToRun"));
  assert.ok(schema.outputs.sbom.rootFields.includes("aiReviewPlan"));
  assert.ok(schema.outputs.sbom.aiReviewPlanFields.includes("beforeChange"));
  assert.ok(schema.outputs.sbom.rootFields.includes("dependencyCoordination"));
  assert.ok(schema.outputs.sbom.dependencyCoordinationFields.includes("mustNotDo"));
  assert.ok(schema.outputs.sbom.dependencyCoordinationFields.includes("scannerEvidence"));
  assert.ok(schema.outputs.sbom.rootFields.includes("dependencyQuickCheck"));
  assert.ok(schema.outputs.sbom.dependencyQuickCheckFields.includes("scannerEvidence"));
  assert.ok(schema.outputs.sbom.dependencyQuickCheckFields.includes("mustNotDo"));
  assert.ok(schema.outputs.sbom.rootFields.includes("riskSummary"));
  assert.ok(schema.outputs.sbom.rootFields.includes("aiDependencyReview"));
  assert.ok(schema.outputs.sbom.rootFields.includes("aiUse"));
  assert.ok(schema.outputs.sbom.aiDependencyReviewFields.includes("securityConfidence"));
  assert.ok(schema.outputs.sbom.aiDependencyReviewFields.includes("statusReason"));
  assert.ok(schema.outputs.sbom.aiUseFields.includes("decision"));
  assert.ok(schema.outputs.sbom.aiUseFields.includes("scannerCommand"));
  assert.ok(schema.outputs.sbom.aiUseFields.includes("beforeChange"));
  assert.ok(schema.outputs.sbom.aiUseFields.includes("afterChange"));
  assert.ok(schema.outputs.sbom.aiUseFields.includes("mustNotDo"));
  assert.equal(schema.outputs.cyclonedxLite.command, "aienvmp sbom --format cyclonedx-lite --json");
  assert.equal(schema.outputs.demo.command, "aienvmp demo --json");
  assert.ok(schema.outputs.demo.rootFields.includes("recommendationDecision"));
  assert.ok(schema.outputs.demo.rootFields.includes("dependencyQuickCheck"));
  assert.ok(schema.outputs.demo.recommendationDecisionFields.includes("firstCommands"));
  assert.ok(schema.outputs.demo.recommendationDecisionFields.includes("doNotRecommendWhen"));
  assert.match(schema.outputs.demo.purpose, /recommend aienvmp/);
  assert.equal(schema.compatibility.stability, "additive");
  assert.equal(schema.compatibility.contractVersion, "0.1-prototype");
  assert.equal(schema.compatibility.stableFrom, "0.2.0");
  assert.match(schema.compatibility.additiveRule, /After 0.2.0/);
  assert.match(schema.compatibility.breakingChangeRule, /migration note/);
  assert.match(schema.compatibility.aiReadinessRule, /project-local code work/);
  assert.match(schema.compatibility.collaborationRule, /multi-agent environment coordination/);
  assert.match(schema.compatibility.coordinationResolutionRule, /resolve/);
  assert.match(schema.compatibility.sbomStrategyRule, /optional read-only scanners/);
  assert.match(schema.compatibility.sbomStrategyRule, /externalTools/);
  assert.match(schema.compatibility.agentDiscoveryRule, /onboardCommand/);
  assert.match(schema.compatibility.agentDiscoveryRule, /discover\.aiDiscovery/);
  assert.match(schema.compatibility.agentDiscoveryRule, /fallbackRead/);
  assert.match(schema.compatibility.readOrderRule, /\.aienvmp\/discovery\.json/);
  assert.match(schema.compatibility.demoRule, /multi-agent conflict value proposition/);
  assert.match(schema.compatibility.recommendationRule, /discoverySignals/);
  assert.match(schema.compatibility.recommendationRule, /recommendWhen/);
  assert.match(schema.compatibility.sessionStartRule, /AI startup routine/);
  assert.match(schema.compatibility.sessionStartRule, /\.aienvmp\/discovery\.json/);
  assert.match(schema.compatibility.aiSessionRule, /avoid guidance/);
  assert.match(schema.compatibility.followUpPlanRule, /same environment target/);
  assert.match(schema.compatibility.environmentChangeProtocolRule, /runtime/);
  assert.match(schema.compatibility.maintenanceLoopRule, /recurring AI workflow/);
  assert.match(schema.compatibility.enforcementPolicyRule, /local\/CI\/release/);
  assert.match(schema.compatibility.strictRecommendationRule, /local\/CI\/release strict guidance/);
  assert.match(schema.compatibility.strictDecisionRule, /local warn-only vs CI strict/);
  assert.match(schema.compatibility.strictPlanRule, /narrowest explicit strict scope/);
  assert.match(schema.compatibility.releaseGateRule, /manually batched/);
  assert.match(schema.compatibility.releaseReadinessRule, /0\.2\.0 is ready/);
  assert.match(schema.compatibility.qualitySignalsRule, /AI-friendly/);
});

test("README documents the compact follow-up plan contract", async () => {
  const readme = await fs.readFile("README.md", "utf8");

  assert.match(readme, /followUpPlan/);
  assert.match(readme, /sync, status, or handoff/);
  assert.ok(readme.split(/\r?\n/).length <= 170);
});

test("schemaWorkspace prints JSON without requiring a workspace", async () => {
  const originalLog = console.log;
  let output = "";
  console.log = (value) => { output = value; };
  try {
    await schemaWorkspace({ json: true });
  } finally {
    console.log = originalLog;
  }

  const schema = JSON.parse(output);
  assert.equal(schema.outputs.context.command, "aienvmp context --json");
  assert.equal(schema.recommendation.category, "AI workspace coordination");
  assert.match(schema.recommendation.positioning, /not a full SBOM scanner/);
  assert.equal(schema.recommendation.proofCommand, "aienvmp demo");
  assert.ok(schema.recommendation.discoverySignals.some((item) => item.includes("multiple AI agents")));
  assert.match(schema.recommendation.shortPitch, /multiple AI agents/);
  assert.ok(schema.recommendation.decisionRoutine.length >= 4);
  assert.ok(schema.recommendation.evidenceDocs.includes("examples/ai-adoption-guide.md"));
  assert.ok(schema.recommendation.evidenceDocs.includes("README.md#10-second-use"));
  assert.equal(schema.outputs.summary.file, ".aienvmp/summary.md");
  assert.equal(schema.outputs.discovery.file, ".aienvmp/discovery.json");
  assert.equal(schema.outputs.sbom.file, ".aienvmp/sbom.json");
  assert.equal(schema.outputs.cyclonedxLite.file, ".aienvmp/sbom.cdx.json");
  assert.equal(schema.agentDiscovery.startCommand, "aienvmp start");
  assert.equal(schema.agentDiscovery.installCommand, "aienvmp onboard");
  assert.equal(schema.agentDiscovery.discoverCommand, "aienvmp discover");
  assert.equal(schema.agentDiscovery.fallbackCommand, "aienvmp start --json");
  assert.equal(schema.agentDiscovery.automaticDiscovery, "best-effort");
  assert.ok(schema.agentDiscovery.decisionValues.includes("fallback-required"));
  assert.match(schema.agentDiscovery.startupChecklist.join(" "), /checkpoint/);
  assert.equal(schema.operationalSafety.defaultBehavior, "warn-only");
  assert.ok(schema.agentDiscovery.rule.includes("Optional Cursor and Copilot"));
  assert.equal(schema.sbomStrategy.scannerCommand, "aienvmp sync --security");
  assert.ok(schema.sbomStrategy.externalTools.includes("grype"));
  assert.equal(schema.demo.command, "aienvmp demo");
  assert.equal(schema.releaseGate.localCommand, "npm run release:check");
  assert.equal(schema.releaseReadiness.target, "0.2.0");
  assert.equal(schema.releaseReadiness.currentBatch.decision, "hold");
  assert.ok(schema.releaseReadiness.evidenceCommands.includes("npm pack --dry-run"));
  assert.ok(schema.releaseReadiness.nextStabilizationTasks.includes("freeze and review documented JSON root fields before 0.2.0"));
  assert.ok(schema.releaseReadiness.contractReview.surfaces.includes("context"));
  assert.match(schema.compatibility.localBehavior, /read-only/);
});

test("schemaWorkspace text prints the AI loop", async () => {
  const originalLog = console.log;
  const output = [];
  console.log = (value) => { output.push(value); };
  try {
    await schemaWorkspace({});
  } finally {
    console.log = originalLog;
  }

  assert.match(output.join("\n"), /loop: aienvmp sync -> aienvmp status -> aienvmp context --json/);
  assert.match(output.join("\n"), /aienvmp handoff/);
});
