import test from "node:test";
import assert from "node:assert/strict";
import fs from "node:fs/promises";
import path from "node:path";

test("packaged aienvmp skill points AI agents to current startup contracts", async () => {
  const skill = await fs.readFile(path.resolve(".agents/skills/aienvmp/SKILL.md"), "utf8");

  assert.match(skill, /npx aienvmp onboard/);
  assert.match(skill, /Use \/ Skip \/ Start/);
  assert.match(skill, /multiple AI agents or humans/);
  assert.match(skill, /full compliance SBOM scanner/);
  assert.match(skill, /AI coordination layer/);
  assert.match(skill, /Syft, Trivy, Grype, Dependency-Track/);
  assert.match(skill, /recommendation\.recommendWhen/);
  assert.match(skill, /recommendation\.doNotRecommendWhen/);
  assert.match(skill, /recommendation\.shortPitch/);
  assert.match(skill, /recommendation\.decisionRoutine/);
  assert.match(skill, /recommendation\.evidenceDocs/);
  assert.match(skill, /examples\/ai-adoption-guide\.md/);
  assert.match(skill, /examples\/ai-workspace-case-study\.md/);
  assert.match(skill, /onboard --agents cursor,copilot/);
  assert.match(skill, /aiSession/);
  assert.match(skill, /\.aienvmp\/README\.md/);
  assert.match(skill, /\.aienvmp\/status\.json/);
  assert.match(skill, /npx aienvmp status --json/);
  assert.match(skill, /artifactFreshness\.state/);
  assert.match(skill, /agentPointers\.discovery/);
  assert.match(skill, /aienvmp discover --json/);
  assert.match(skill, /aiDiscovery/);
  assert.match(skill, /Automatic discovery is best-effort/);
  assert.match(skill, /discovery:/);
  assert.match(skill, /followUpPlan/);
  assert.match(skill, /nextCommand/);
  assert.match(skill, /npx aienvmp sync/);
  assert.match(skill, /npx aienvmp demo/);
  assert.match(skill, /review-before-env-change/);
  assert.match(skill, /without heavy locks or surprise failures/);
  assert.match(skill, /Local source edits can continue/);
});
